### ISSUE TITLE
yarn test:coverage fails

### ISSUE THREAD

**Issue by ozaytsev86** [ozaytsev86/react-leaflet-waypoints#1]
When run `yarn test:coverage`  it fails with error ` Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.`

**Comment by danielphilipjohnson** [comment]
By renaming Map.jsx to Map.js this error disappears. So, It might be an issue with the test not picking up jsx files.

**Comment by ozaytsev86** [comment]
Thanks a lot @danielphilipjohnson gonna try it.

**Comment by danielphilipjohnson** [comment]
Hey no problem. It’s raro that mocha test work with the jsx file but code coverage with Istanbul won’t. 

I tried to use this inside the nyc file and it didn’t change anything.
extensions: ['.js', '.jsx']


Because it mentions an error related to imports I suspect it’s related to this


by default, Mocha only knows ES5 and you are not able to test ES6/ES7 or *.jsx.

So it might be worth trying this in the test command 

test nyc –extension .jsx –extension .es6

**Comment by ozaytsev86** [comment]
I use mocha and nyc in other projects and they have never had this problem, I will check the configuration, may be I miss something. Also mention that definitely I have to clean and update the deps and configs here :D

**Comment by danielphilipjohnson** [comment]
It’s definitely weird that a file extension 😅 stops it working. I hope I managed to help even if it was a little. :D

**Comment by ozaytsev86** [comment]
@danielphilipjohnson sure, more than you think ;)
